name: Hello Deepanshu Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  USER_NAME: "Massom" # Global Env Variable

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello $USER_NAME!"
