



name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment

      run: echo "Deploying to $APP_ENV"
       env:
         APP_ENV: masoom
