name: CD depend on CI jobs
on: 
 push:
   branches:
     - main

jobs:
  job_once_CI:
    name: Build and Test
    run-on: ubuntu-latest
    steps:
      - name: checkout respository
        uses: actions/checkout@v4
      
      - name: Run test steps
        run: echo"Runnig tests for CI..."
  jobs_two_CD:
    name: Deployement for application:
    needs: job_once_CI
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment for the application part
        run: echo "JOb CI & CD done successfully"
