name: Mrko artificats chahiye job1 se toh fir job2 mein use kar saku
on: [push]

jobs:
  build-dee-artificat: # unique job name 
    runs-on: ubuntu-latest # machine os
    steps: # decide to choose command to exicutions
      - uses: actions/checkout@v4  ## git clone github repor url on the created machine --> filess saree git repo file utha ke vm mein laa dega jese tere llocal system pe
      - name: create dee build uska out  # name
        run: | # pipe is used for command exicution line by line
          mkdir dee
          echo "Hello dee artifcats ka content hai ye jo mein a simple file mein use kr raha hu" > dee/app.txt
      - name: Upload dee artificat # name
        uses: actions/upload-artifact@v4
        with:
          name: dee-build-files
          path: dee/
  deploy-dee-artificats:
    needs: build-dee-artificat
    runs-on: ubuntu-latest
    steps: # to run command 
      - name: Download dee artificats files from build-dee-artificat
        uses: actions/download-artifact@v4
        with:
          name: dee-build-files
          path: downloaded-dist/
      - name: Read the build file from build-dee-artificat 
        run: cat downloaded-dist/app.txt

